In [1]:
import cvxpy as cp
import numpy as np

# Generate a random non-trivial quadratic program.
m = 15
n = 10
p = 5
np.random.seed(1)
P = np.random.randn(n, n)
P = P.T @ P
P = np.diag(np.random.randn(n))
P = np.eye(n)
q = np.random.randn(n)
G = np.random.randn(m, n)
h = G @ np.random.randn(n)
A = np.random.randn(p, n)
b = np.random.randn(p)

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize((1/2)*cp.quad_form(x, P) ),
                 [G @ x <= h,
                  A @ x == b])
prob.solve()

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution corresponding to the inequality constraints is")
print(prob.constraints[0].dual_value)



The optimal value is 9.063118911643306
A solution x is
[ 0.99074089  1.59660042 -1.25436095 -0.54917709 -0.09104013 -0.24366265
 -2.60062036  0.86514129 -2.24678093 -0.30518933]
A dual solution corresponding to the inequality constraints is
[0.         3.45434164 0.         0.         0.         0.
 0.         0.         0.         0.         1.72202135 0.
 0.         0.34588447 2.5678154 ]


In [17]:
print(cp.installed_solvers())

['CLARABEL', 'CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']


In [16]:
import scipy 
x0 = np.random.randn(n)
func = lambda x: 1/2*x.T @ P @ x 
cons = ({'type': 'ineq', 'fun': lambda x:  - G @ x + h},
        {'type': 'eq', 'fun': lambda x: A @ x - b },
        )
scipy.optimize.minimize(func, x0, constraints=cons)

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 9.063118911643233
       x: [ 9.907e-01  1.597e+00 -1.254e+00 -5.492e-01 -9.104e-02
           -2.437e-01 -2.601e+00  8.651e-01 -2.247e+00 -3.052e-01]
     nit: 2
     jac: [ 9.907e-01  1.597e+00 -1.254e+00 -5.492e-01 -9.104e-02
           -2.437e-01 -2.601e+00  8.651e-01 -2.247e+00 -3.052e-01]
    nfev: 23
    njev: 2

In [1]:
import numpy as np
import scipy
def func(x,a):
    cost = a@cp.vstack([(x**2).reshape((-1,1),'C'),np.ones((1,1))])
    return cost 


a = np.array([1,2,3,4,5,7])
x0 = np.array([2,3,4,5,6])
# print(a@x0)
fun = lambda x: func(x,a)
# cons = ({'type':'ineq','fun': lambda x: x})
# scipy.optimize.minimize(fun,x0, constraints=cons)

#-----------------cxvpy--------
import cvxpy as cp 
xx = cp.Variable((5,1))
print(cp.vec(xx@xx.T).shape,xx[0].shape)
xxx = cp.Variable(5)
print(cp.hstack((xxx,np.array([1,2,3]))))
print(cp.vstack([xx,np.ones((1,1))]))
print(cp.outer(xxx,xxx).shape)
prob = cp.Problem(cp.Minimize(fun(xx)), [xx>=0])
prob.solve()
print(prob.value,xx.value)

(25,) (1,)
Hstack(var6, [1. 2. 3.])
Vstack(var1, [[1.]])
(5, 5)
7.0 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [3]:
A = np.arange(9).reshape(3,3)
idx = np.where((A[1][1:]>3) & (A[1][1:]<5))[0]
print(idx, A[1,idx],A[1,1])
B = {}
B['a'] =1 
print(B)
A[2] =0
print(A)

[0] [3] 4
{'a': 1}
[[0 1 2]
 [3 4 5]
 [0 0 0]]


In [26]:
A = np.intersect1d(np.array([1,2]),np.array([4]))
print(A.size)

0


In [14]:
A = np.arange(9).reshape(3,3)
BB = 2*A

print(A.shape)
B = np.array([True, False, True])
print(1-np.asarray(B))
BB[0][B] = A[0][~B]
print(BB@np.ones(3))


(3, 3)
[0 1 0]
[ 4. 24. 42.]
